Byte.Attack/Controllers/EspecialistaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ByteAttack.Models;
using ByteAttack.Repositorio;

namespace Byte.Attack.Controllers
{
    public class EspecialistaController : Controller
    {
        // GET: Funcionario
        public ActionResult Especialista()
        {
            var especialista = new Especialista();
            return View(especialista);
        }
        Acoes ac = new Acoes();

        [HttpPost]
        public ActionResult CadEspecialista(Especialista especialista)
        {
            ac.CadastrarEspecialista(especialista);
            return View(especialista);
        }

        public ActionResult ListarEspecialista()
        {
            var ExibirEspec = new Acoes();
            var TodosEspec = ExibirEspec.ListarEspecialista();
            return View(TodosEspec);
        }
    }
}

Byte.Attack/Controllers/FuncionarioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ByteAttack.Models;
using ByteAttack.Repositorio;

namespace Byte.Attack.Controllers
{
    public class FuncionarioController : Controller
    {
        // GET: Funcionario
        public ActionResult Funcionario()
        {
            var funcionario = new Funcionario();
            return View(funcionario);
        }
        Acoes ac = new Acoes();

        [HttpPost]
        public ActionResult CadFuncionario(Funcionario funcionario)
        {
            ac.CadastrarFuncionario(funcionario);
            return View(funcionario);
        }

        public ActionResult ListarFuncionario()
        {
            var ExibirFunc = new Acoes();
            var TodosFunc = ExibirFunc.ListarFuncionario();
            return View(TodosFunc);
        }
    }
}

Byte.Attack/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Byte.Attack.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Byte.Attack/Controllers/ProcedimentoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ByteAttack.Models;
using ByteAttack.Repositorio;

namespace Byte.Attack.Controllers
{
    public class ProcedimentoController : Controller
    {
        // GET: Funcionario
        public ActionResult Procedimento()
        {
            var procedimento = new Procedimento();
            return View(procedimento);
        }
        Acoes ac = new Acoes();

        [HttpPost]
        public ActionResult CadProcedimento(Procedimento procedimento)
        {
            ac.CadastrarProcedimento(procedimento);
            return View(procedimento);
        }

        public ActionResult ListarProcedimento()
        {
            var ExibirProc = new Acoes();
            var TodosProc = ExibirProc.ListarProcedimento();
            return View(TodosProc);
        }
    }
}

Byte.Attack/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Byte.Attack/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Byte.Attack/Views/Home/Index.cshtml
@{ ViewBag.Title = "Home Page"; }

<style>
    .container .index {
        margin-top: 17%;
       
    }
    .LogoIndex{
        padding-bottom:50px;
        margin-left:80%;
    }
    .h3Index{
        color:red;
        padding: 0px 280px 30px;
    }
   


    /*.container .buttons {
       background: #ffffff;
       border: 1px solid #ee1111;
    }*/
    .container .buttonsIndex {
        padding: 10px 450px;
    }
    .container .index #IndexTel{
        border:1px solid red
    }
    .container .index .buttonsIndex img{
      height:50px;
    }
    .container .buttonsIndex a {
        text-decoration: none;
        color: red;
        font-size: 24px;
        display: inline;
        padding: 0px 2px;
    }

    .container  .buttonsIndex a:hover {
            color: #000;
    }
    
    
 
    
</style>



<div class="container index">
    <h3 class="h3Index">Bem-vindo ao sistema Narcissus Clínica de Estética!</h3>
    <img src="~/Imagens/WhatsApp Image 2021-11-12 at 11.50.33.jpeg" style="width: 210px" class="LogoIndex" />
    <div id="IndexTel">
        <div class="buttonsIndex">
            <img src="~/Imagens/pergunta-do-cliente.png"  style="padding-left:10px;"/>@Html.ActionLink("Cliente", "ListarCliente", "Cliente")
        </div>
        <div class="buttonsIndex">
            <img src="~/Imagens/funcionarios.png" /> @Html.ActionLink("Assistentes", "ListarFuncionario", "Funcionario")
        </div>
        <div class="buttonsIndex">
            <img src="~/Imagens/procedimento.png"/>@Html.ActionLink("Procedimentos", "ListarProcedimento", "Procedimento")
        </div>
        <div class="buttonsIndex">
            <img src="~/Imagens/especialista.png" />@Html.ActionLink("Especialistas", "ListarEspecialista", "Especialista")
        </div>
        <!--Botao sair provisório-->
    </div>
</div>