Byte.Attack/Controllers/ClienteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ByteAttack.Models;
using ByteAttack.Repositorio;


namespace ByteAttack.Controllers
{
    public class ClienteController : Controller
    {
        // GET: Cliente
        public ActionResult Cliente()
        {
            var cliente = new Cliente(); // aqui criamos o projeto
            return View(cliente); // Retornamos para a view dados
        }
        Acoes ac = new Acoes();

        [HttpPost]
        public ActionResult CadCliente(Cliente cliente)
        {
            ac.CadastrarClientes(cliente);
            return View(cliente);
        }

        public ActionResult ListarCliente()
        {
            var ExibirClie = new Acoes();
            var TodosClie = ExibirClie.ListarCliente();
            return View(TodosClie);
        }
    }
}

Byte.Attack/Controllers/FuncionarioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ByteAttack.Models;
using ByteAttack.Repositorio;

namespace Byte.Attack.Controllers
{
    public class FuncionarioController : Controller
    {
        // GET: Funcionario
        public ActionResult Funcionario()
        {
            var funcionario = new Funcionario();
            return View(funcionario);
        }
        Acoes ac = new Acoes();

        [HttpPost]
        public ActionResult CadFuncionario(Funcionario funcionario)
        {
            ac.CadastrarFuncionario(funcionario);
            return View(funcionario);
        }

        public ActionResult ListarFuncionario()
        {
            var ExibirFunc = new Acoes();
            var TodosFunc = ExibirFunc.ListarFuncionario();
            return View(TodosFunc);
        }
    }
}

Byte.Attack/Controllers/ProcedimentoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ByteAttack.Models;
using ByteAttack.Repositorio;

namespace Byte.Attack.Controllers
{
    public class ProcedimentoController : Controller
    {
        // GET: Funcionario
        public ActionResult Procedimento()
        {
            var procedimento = new Procedimento();
            return View(procedimento);
        }
        Acoes ac = new Acoes();

        [HttpPost]
        public ActionResult CadProcedimento(Procedimento procedimento)
        {
            ac.CadastrarProcedimento(procedimento);
            return View(procedimento);
        }

        public ActionResult ListarProcedimento()
        {
            var ExibirProc = new Acoes();
            var TodosProc = ExibirProc.ListarProcedimento();
            return View(TodosProc);
        }
    }
}

Byte.Attack/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Meu Aplicativo ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <style>
        .navbar {
            border-color: #ff0000;
        }

        footer p {
            color: #ff0000;
        }

        .nav li {
            padding-top: 10px;
            color: red;
        }
    </style>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top" style="background:#fff">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <div class="nav navbar-nav navbar-left " style="margin-right:100px">
                    <img src="~/Imagens/WhatsApp Image 2021-11-12 at 11.50.33.jpeg"  style="width: 210px" />
                </div>
                
                
            </div>
            @if (Session["usuarioLogado"] != null)
            {
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Início", "Index", "Home")</li>
                        
                        <li>@Html.ActionLink("Cadastrar Funcionário", "Funcionario", "Funcionario")</li>
                        <li>@Html.ActionLink("Cadastrar Cliente", "Cliente", "Cliente")</li>
                        <li>@Html.ActionLink("Cadastrar Procedimentos", "Procedimento", "Procedimento")</li>
                      


                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li>@Html.ActionLink("Logout", "Login", "Login/Logout")</li>
                        <li>@Html.ActionLink(@Session["usuarioLogado"].ToString(), "Login", "Login/Logout")</li>

                    </ul>
                </div>
            }
            else
            {
                <ul class="nav navbar-nav navbar-right">
                    <li>@Html.ActionLink("Login", "Login", "Login")</li>
                </ul>
            }
        </div>
    </div>
    <div class="container body-content">
        @* para não ficar em loop infinito pega a url e verificar se contém a palavar login para carregar no centro da pagina *@
        @if (Session["usuarioLogado"] != null || HttpContext.Current.Request.AppRelativeCurrentExecutionFilePath.Contains("Login"))
        {
            @RenderBody()
        }
        else
        {
            Context.Response.Redirect("/Login/Login");
        }

        <hr />
        <footer>
            <p style="text-align:center">&copy; @DateTime.Now.Year - BYTE.ATTACK- TODOS OS RESERVADOS</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>

</body>
</html>